### ISSUE TITLE
After upgrading onlyoffice app to 9.7.0, there are a lot of critical error.

### ISSUE THREAD

**Issue by git-ikeda** [ONLYOFFICE/onlyoffice-nextcloud#1078]
ArgumentCountError
Too few arguments to function OCA\Onlyoffice\AppConfig::__construct(), 1 passed in /var/www/html/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php on line 76 and exactly 4 expected
Could not boot documentserver_community: Too few arguments to function OCA\Onlyoffice\AppConfig::__construct(), 1 passed in /var/www/html/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php on line 76 and exactly 4 expected

Nextcloud 30.0.6 with PHP 8.3.19 on Ubuntu 22.04.5 LTS

**Comment by Ceelight** [comment]
Same here.

**Comment by panivanes** [comment]
The same issue.
Last working version - 9.5.0

**Comment by micker** [comment]
Same here !

**Comment by Albirew** [comment]
Disabled app for now as this error makes the whole cron job to fail.

PS: instead of commenting "same here", you should add a reaction on OP (like the 👍), and if you wanna follow updates, there's the notification subscribe button over the right -->

**Comment by micker** [comment]
sorry but if you disable it only office doesn't work not ?

**Comment by Albirew** [comment]
right, but cron job not working is a worse choice in the long run for me (you'll lose all notifications, planned jobs won't run, etc.)

**Comment by droumanet** [comment]
Confirmed on synology and nextcloud (through Container apps, it's Docker)
- Community Document server 0.1.20
- OnlyOffice 9.7.0
- Nexcloud 31.0.2

Error:  
`ArgumentCountError` Too few arguments to function OCA\Onlyoffice\AppConfig::__construct(), 1 passed in /var/www/html/apps/documentserver_community/lib/AppInfo/Application.php on line 76 and exactly 4 expected
Could not boot documentserver_community: Too few arguments to function OCA\Onlyoffice\AppConfig::__construct(), 1 passed in /var/www/html/apps/documentserver_community/lib/AppInfo/Application.php on line 76 and exactly 4 expected`

Cron is blocked, so it has major impact on calendar and other nexcloud background tasks.

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).

**Comment by droumanet** [comment]
Thanks for this information.
I was falling on this issue after a search on internet.
