### ISSUE TITLE
jwt errors on nextcloud 25.0.7

### ISSUE THREAD

**Issue by blackwhitebear8** [ONLYOFFICE/onlyoffice-nextcloud#825]
I m unable to use onlyoffice on my nextcloud server becouse it wont connect anymore after updating to 25.0.7.

I m seeing this error in teh logs: 
Too few arguments to function Firebase\JWT\JWT::encode(), 2 passed in /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php on line 296 and at least 3 expected in file '/var/www/nextcloud/apps/oidc/vendor/firebase/php-jwt/src/JWT.php' line 188

**Comment by duckhawk** [comment]
Same problem with 26.0.2 on my server.

**Comment by duckhawk** [comment]
But after this changes I got "Error while downloading the document file to be converted."
I don't know, if this problems caused by one reason, or not.

**Comment by blackwhitebear8** [comment]
how can i get this "fix" so i can try it?

**Comment by blackwhitebear8** [comment]
it shows this in teh logs 3 times here first and then the document error:

[onlyoffice] Fatal: Download empty with empty or not correct hash: "kid" empty, unable to lookup correct key

**Comment by adam42a** [comment]
Don't know how github works with these operations like 'merged' and 'pull' but if this issue is fixed, I'm not seeing any fix in the wild. 

I got caught by the same NextCloud upgrade as BlackWhiteBear. I hope you guys were able to mark the OnlyOffice app version as 'not compatible' before anyone else got trapped by it too.

I'm on app version 7.8.0 - when is a release going to come out with the fix in it please? This is pretty critical. It's difficult enough as it is to get people to work on the cloud, this really gives them more reason to hesitate :(

**Comment by blackwhitebear8** [comment]
for the poeple wondering what i did i switched to collabora code server (nextclud office) has way more features tbh and is way faster

**Comment by manuelschneider** [comment]
You can backport the changes to the current 8.1.0 with the 2 attached patches.

Just go to the root of your app and apply them with `patch -p1 < ..patch`

[0001-full-patch-from-https-github.com-ONLYOFFICE-onlyoffi.patch.log](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/files/12304710/0001-full-patch-from-https-github.com-ONLYOFFICE-onlyoffi.patch.log)
[0002-hotfix-downloading.patch.log](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/files/12304714/0002-hotfix-downloading.patch.log)


(!) I've renamed the files, because github did not like '.patch'.
