### PR TITLE
Added algorithm for jwt php lib func

### LINKED ISSUE #825: jwt errors on nextcloud 25.0.7
I m unable to use onlyoffice on my nextcloud server becouse it wont connect anymore after updating to 25.0.7.

I m seeing this error in teh logs: 
Too few arguments to function Firebase\JWT\JWT::encode(), 2 passed in /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php on line 296 and at least 3 expected in file '/var/www/nextcloud/apps/oidc/vendor/firebase/php-jwt/src/JWT.php' line 188

### PR DESCRIPTION
**Pull request by duckhawk**
Added algorithm param in JWT encode

Fix #825

### CODE REVIEW

**Comment by LinneyS** [comment]
Thank's
done at #844
